try:
    pass
except Exception as e:
    print(e)
finally:
    pass